{% set name = "msal_requests_auth" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 905d42ae0f254fe8589de68056e56cc14c7093ae8a91c5a304d5917939312b67

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - msal
    - requests
    - pyperclip

test:
  imports:
    - msal_requests_auth
    - msal_requests_auth.auth

about:
  home: https://github.com/corteva/msal-requests-auth
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Authentication using python requests and MSAL.
  description: |
    Authentication using python requests and MSAL.
    This uses the MSAL cache for repeated requests. 
  doc_url: https://github.com/corteva/msal-requests-auth
  dev_url: https://github.com/corteva/msal-requests-auth

extra:
  recipe-maintainers:
    - snowman2
