{% set python_min = "3.10" %}
{% set name = "msal_requests_auth" %}
{% set version = "0.9.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0b611309117de6846febfa16df42f39a31b474251fc162fdc3fc77c665c0d1b2

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - msal
    - requests
    - pyperclip
    - platformdirs

test:
  requires:
    - python {{ python_min }}
  imports:
    - msal_requests_auth
    - msal_requests_auth.auth

about:
  home: https://github.com/corteva/msal-requests-auth
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Authentication using python requests and MSAL.
  description: |
    Authentication using python requests and MSAL.
    This uses the MSAL cache for repeated requests. 
  doc_url: https://github.com/corteva/msal-requests-auth
  dev_url: https://github.com/corteva/msal-requests-auth

extra:
  recipe-maintainers:
    - snowman2
